export const UiCategories = [
    'activity-feeds',
    'boards',
    'dashboards',
    'editors',
    'empty-states',
    'libraries',
    'lists-tables',
    'nudges',
    'settings',
    'auth',
    'forms',
    'profiles',
    'analytics-metrics-stats',
] as const
